version: "3"
services:
  develop:
    build: .
    ports:
      - "5000:5000"
    container_name: proxy-service-develop
    environment:
      PORT: 5000
      NODE_PATH: app/src
      GATEWAY_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:5000
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      URLS: google#https://www.google.com
      FASTLY_ENABLED: "false"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
    command: develop
    volumes:
      - ./app:/home/proxy-service/app
