version: "3"
services:
  develop:
    build: .
    ports:
      - "5000:5000"
    container_name: proxy-service-develop
    environment:
      PORT: 5000
      NODE_PATH: app/src
      CT_REGISTER_MODE: auto
      CT_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:5000
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      API_VERSION: v1
      URLS: google#https://www.google.com
      FASTLY_ENABLED: "false"
    command: develop
    volumes:
      - ./app:/home/proxy-service/app
